version: "3.7"

services:
  qr_backend:
    image: node:16
    container_name: qr_backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "npm install && npm run dev"
